import { ISelectItem } from '@interfaces/ISelectItem'

const areasOfExpertiseItems: ISelectItem[] = [
  { label: 'Acupuntura', value: 'acupuntura' },
  { label: 'Alergia e imunologia', value: 'alergia_e_imunologia' },
  { label: 'Anestesiologia', value: 'anestesiologia' },
  { label: 'Angiologia', value: 'angiologia' },
  { label: 'Cardiologia', value: 'cardiologia' },
  { label: 'Cirurgia cardiovascular', value: 'cirurgia_cardiovascular' },
  { label: 'Cirurgia da mão', value: 'Cirurgia_da_mao' },
  {
    label: 'Cirurgia de cabeça e pescoço',
    value: 'cirurgia_de_cabeça_e_pescoco',
  },
  {
    label: 'Cirurgia do aparelho digestivo',
    value: 'cirurgia_do_aparelho_digestivo',
  },
  { label: 'Cirurgia geral', value: 'cirurgia_geral' },
  { label: 'Cirurgia oncológica', value: 'cirurgia_oncologica' },
  { label: 'Cirurgia pediátrica', value: 'cirurgia_pediatrica' },
  { label: 'Cirurgia plástica', value: 'cirurgia_plastica' },
  { label: 'Cirurgia torácica', value: 'Cirurgia_toracica' },
  { label: 'Cirurgia vascular', value: 'cirurgia_vascular' },
  { label: 'Clínica médica', value: 'clinica_medica' },
  { label: 'Coloproctologia', value: 'coloproctologia' },
  { label: 'Dermatologia', value: 'dermatologia' },
  {
    label: 'Endocrinologia e metabologia',
    value: 'endocrinologia_e_metabologia',
  },
  { label: 'Endoscopia', value: 'endoscopia' },
  { label: 'Gastroenterologia', value: 'gastroenterologia' },
  { label: 'Genética médica', value: 'genetica_medica' },
  { label: 'Geriatria', value: 'geriatria' },
  { label: 'Ginecologia e obstetrícia', value: 'ginecologia_e_obstetricia' },
  { label: 'Hematologia e hemoterapia', value: 'hematologia_e_hemoterapia' },
  { label: 'Homeopatia', value: 'homeopatia' },
  { label: 'Infectologia', value: 'infectologia' },
  { label: 'Medicina de emergência', value: 'medicina_de_emergencia' },
  {
    label: 'Medicina de família e comunidade',
    value: 'medicina_de_familia_e_comunidade',
  },
  { label: 'Medicina do trabalho', value: 'medicina_do_trabalho' },
  { label: 'Medicina de tráfego', value: 'medicina_de_trafego' },
  { label: 'Medicina esportiva', value: 'medicina_esportiva' },
  {
    label: 'Medicina física e reabilitação',
    value: 'medicina_fisica_e_reabilitacao',
  },
  { label: 'Medicina intensiva', value: 'medicina_intensiva' },
  {
    label: 'Medicina legal e perícia médica',
    value: 'medicina_legal_e_pericia_medica',
  },
  { label: 'Medicina nuclear', value: 'medicina_nuclear' },
  {
    label: 'Medicina preventiva e social',
    value: 'medicina_preventiva_e_social',
  },
  { label: 'Nefrologia', value: 'nefrologia' },
  { label: 'Neurocirurgia', value: 'neurocirurgia' },
  { label: 'Neurologia', value: 'neurologia' },
  { label: 'Nutrologia', value: 'nutrologia' },
  { label: 'Oftalmologia', value: 'oftalmologia' },
  { label: 'Oncologia clínica', value: 'oncologia_clinica' },
  { label: 'Ortopedia e traumatologia', value: 'ortopedia_e_traumatologia' },
  { label: 'Otorrinolaringologia', value: 'otorrinolaringologia' },
  { label: 'Patologia', value: 'patologia' },
  {
    label: 'Patologia clínica/medicina laboratorial',
    value: 'patologia_clínica_medicina_laboratorial',
  },
  { label: 'Pediatria', value: 'pediatria' },
  { label: 'Pneumologia', value: 'pneumologia' },
  { label: 'Psiquiatria', value: 'psiquiatria' },
  {
    label: 'Radiologia e diagnóstico por imagem',
    value: 'radiologia_e_diagnostico_por_imagem',
  },
  { label: 'Radioterapia', value: 'radioterapia' },
  { label: 'Reumatologia', value: 'reumatologia' },
  { label: 'Urologia', value: 'urologia' },
]

export { areasOfExpertiseItems }
